name 'jballou-hlstatsx'
version '0.0.1'
author 'jballou'
license 'Apache License, Version 2.0'
project_page 'https://github.com/jaredballou/puppet-hlstatsx'
source 'UNKNOWN'
summary 'This class manages the HLStatsX application'
description 'This module manages HLStatsX, a stat and log aggregator and interfacing tool used with a number of online games based on the Source engine. The module installs and provides defined types for managing installing, users, games, and servers.'
